name: recipe_grocery
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0-234.0.dev <4.0.0"

dependencies:
  cached_network_image: ^3.3.0
  chopper: ^7.0.9
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_slidable: ^3.0.1
  flutter_svg: ^2.0.9
  http: ^1.1.0
  json_annotation: ^4.8.1
  logging: ^1.2.0
  platform: ^3.1.3
  provider: ^6.1.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  chopper_generator: ^7.0.6

flutter:
  uses-material-design: true

  assets:
    - assets/recipes1.json
    - assets/recipes2.json
    - assets/images/
